# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saying',
            old_name='author',
            new_name='speaker',
        ),
    ]
